spring.application.name=PokeApiService
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=bunnymailcom419@gmail.com
spring.mail.password=vopj ddfi vieg drkl
spring.mail.properties.mail.smtp.atuh=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.protocol=smtp